apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.26.2
appVersion: 4.16.1-20231212
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
dependencies:
- repository: https://kedacore.github.io/charts
  version: 2.12.0
  name: keda
  condition: autoscaling.enabled
maintainers:
  - name: SeleniumHQ
    email: selenium-developers@googlegroups.com
sources:
  - https://github.com/SeleniumHQ/docker-selenium
