name: Test video files

on:
  push:
    paths-ignore:
      - '.circleci/**'
  pull_request:
    paths-ignore:
      - '.circleci/**'

permissions:
  contents: read

jobs:
  build-and-test:
    name: Test video recorded through Docker Selenium
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Output Docker info
        run: docker info
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          check-latest: true
      - name: Get branch name (only for push to branch)
        if: github.event_name == 'push'
        run: echo "BRANCH=$(echo ${PUSH_BRANCH##*/})" >> $GITHUB_ENV
        env:
          PUSH_BRANCH: ${{ github.ref }}
      - name: Get target branch name (only for PRs)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH=$(echo ${TARGET_BRANCH##*/})" >> $GITHUB_ENV
        env:
          TARGET_BRANCH: ${{ github.head_ref }}
      - name: Output branch name
        run: echo ${BRANCH}
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Run Docker Compose to record video
        run: USE_RANDOM_USER_ID=${USE_RANDOM_USER} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} make test_video
      - name: Upload recorded Chrome video
        uses: actions/upload-artifact@v4
        with:
          name: chrome_video
          path: ./tests/videos/chrome_video.mp4
      - name: Upload recorded Chromium video
        uses: actions/upload-artifact@v4
        with:
          name: chromium_video
          path: ./tests/videos/chromium_video.mp4
      - name: Upload recorded Edge video
        uses: actions/upload-artifact@v4
        with:
          name: edge_video
          path: ./tests/videos/edge_video.mp4
      - name: Upload recorded Firefox video
        uses: actions/upload-artifact@v4
        with:
          name: firefox_video
          path: ./tests/videos/firefox_video.mp4
